### PR TITLE
Fix a class cast exception if the key is as String

### PR DESCRIPTION
**Pull request by ckosmowski**

### CODE REVIEW

**Comment by laymain** [comment]
Hi,

Thanks for your contribution.
Could you provide a schema to reproduce the underlying issue?

**Comment by ckosmowski** [comment]
The schema should be:
```
{type: "string"}
```
Such schemas seems to be called "primitive schemas" in the avro environment.

That is what you get if you use `AvroSchemaUtils.getSchema("MyStringKey")` and this is used by `AbstractKafkaAvroSerializer` if you ask it to serialize a simple String.

This is what is stored in the schema registry:
```
 {
    "topic": "_schemas",
    "key": {
      "subject": "dpxStatusAvroReg-key",
      "version": 1,
      "magic": 1,
      "keytype": "SCHEMA"
    },
    "value": {
      "subject": "dpxStatusAvroReg-key",
      "version": 1,
      "id": 2,
      "schema": "\"string\"",
      "deleted": false
    },
    "partition": 0,
    "offset": 22
  },
```

i hope this helps.

**Comment by laymain** [comment]
Thanks for your input, I'll dig into it

**Comment by laymain** [comment]
How it's handled in the AbstractKafkaAvroDeserializer: https://github.com/confluentinc/schema-registry/blob/0f3aebd9290208c8439434d6315f989832ce8472/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroDeserializer.java#L127

**Comment by laymain** [comment]
Provided code was not compiling, but thank you for pointing out this issue.
I have released a new version with a more generic fix:
https://github.com/laymain/kafka-tool-avro/commit/683624545ffab00d46a36c83d9c9d266ba67fae2

**Pull request merged**
